# Generated by Django 6.0.4 on 2026-05-11 16:42

import django.db.models.deletion
import django_enum.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0013_remove_jobseeker_resume_file'),
        ('jobs', '0006_alter_job_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobAdvice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', django_enum.fields.EnumPositiveSmallIntegerField(choices=[(0, 'Pending'), (1, 'Ready'), (2, 'Failed')], default=0, verbose_name='status')),
                ('advice', models.JSONField(blank=True, help_text='Structured AI advice: {suitability, summary, matching_skills, missing_skills, strengths, areas_to_improve, recommendations}', null=True, verbose_name='advice')),
                ('language', models.CharField(default='en', help_text='Language code for advice (e.g. "en", "ru")', max_length=10, verbose_name='language')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='error message')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='expires at')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advices', to='jobs.job', verbose_name='job')),
                ('jobseeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_advices', to='accounts.jobseeker', verbose_name='job seeker')),
            ],
            options={
                'verbose_name': 'job advice',
                'verbose_name_plural': 'job advices',
                'db_table': 'job_advices',
                'indexes': [models.Index(fields=['status'], name='job_advices_status_3b0f65_idx'), models.Index(fields=['expires_at'], name='job_advices_expires_13bdce_idx')],
                'constraints': [models.UniqueConstraint(fields=('jobseeker', 'job'), name='unique_job_advice_per_jobseeker'), models.CheckConstraint(condition=models.Q(('status__in', [0, 1, 2])), name='job_advice_JobAdvice_status_JobAdviceStatusEnum')],
            },
        ),
    ]
