# Generated by Django 6.0.4 on 2026-04-28 14:55

import django_enum.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_type',
            field=django_enum.fields.EnumPositiveSmallIntegerField(choices=[(0, 'Empty'), (1, 'Employer'), (2, 'Company')], default=0),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('account_type__in', [0, 1, 2])), name='accounts_User_account_type_AccountTypeEnum'),
        ),
    ]
