# Generated by Django 6.0.4 on 2026-04-29 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_industry_user_email_verification_code_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='company',
            name='accounts_Company_size_CompanySizeEnum',
        ),
        migrations.RemoveField(
            model_name='company',
            name='industry',
        ),
        migrations.RemoveField(
            model_name='company',
            name='recruiter',
        ),
        migrations.DeleteModel(
            name='Industry',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
    ]
