# Generated by Django 6.0.4 on 2026-05-04 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_company_accounts_company_size_companysizeenum_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseeker',
            name='about',
            field=models.TextField(blank=True, default='', verbose_name='about'),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='avatar',
            field=models.ImageField(blank=True, default='', upload_to='jobseeker/avatars/', verbose_name='avatar'),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='location',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='location'),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='phone'),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='title',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='title'),
        ),
    ]
