# Generated by Django 6.0.4 on 2026-05-04 10:19

import django.db.models.deletion
import django_enum.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_jobseeker_about_jobseeker_avatar_jobseeker_location_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('level', django_enum.fields.EnumPositiveSmallIntegerField(choices=[(0, 'Average'), (1, 'Secondary special'), (2, 'Unfinished higher education'), (3, 'Higher'), (4, 'Bachelor'), (5, 'Master'), (6, 'Candidate of Sciences'), (7, 'Doctor of Science')], default=0)),
                ('institution_name', models.CharField(max_length=200, verbose_name='institution name')),
                ('faculty', models.CharField(blank=True, default='', max_length=200, verbose_name='faculty')),
                ('specialization', models.CharField(blank=True, default='', max_length=200, verbose_name='specialization')),
                ('year_of_graduation', models.PositiveIntegerField(blank=True, null=True, verbose_name='year of graduation')),
                ('jobseeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education', to='accounts.jobseeker', verbose_name='job seeker')),
            ],
            options={
                'verbose_name': 'education',
                'verbose_name_plural': 'education',
                'db_table': 'education',
                'ordering': ['-year_of_graduation'],
                'constraints': [models.CheckConstraint(condition=models.Q(('level__in', [0, 1, 2, 3, 4, 5, 6, 7])), name='accounts_Education_level_EducationLevelEnum')],
            },
        ),
    ]
