# Generated by Django 6.0.4 on 2026-05-04 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_education'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position', models.CharField(max_length=200, verbose_name='position')),
                ('company_name', models.CharField(max_length=200, verbose_name='company name')),
                ('start_date', models.DateField(verbose_name='start date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='end date')),
                ('description', models.TextField(blank=True, default='', verbose_name='description')),
                ('jobseeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experience', to='accounts.jobseeker', verbose_name='job seeker')),
            ],
            options={
                'verbose_name': 'experience',
                'verbose_name_plural': 'experience',
                'db_table': 'experience',
                'ordering': ['-start_date'],
            },
        ),
    ]
