# Generated by Django 6.0.4 on 2026-05-04 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_experience'),
        ('jobs', '0002_jobapplication_cover_letter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseeker',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='jobseekers', to='jobs.skill', verbose_name='skills'),
        ),
    ]
