# Generated by Django 6.0.4 on 2026-05-04 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_jobseeker_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseeker',
            name='profile_visible',
            field=models.BooleanField(default=True, verbose_name='profile visible'),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='resume_public',
            field=models.BooleanField(default=True, verbose_name='resume public'),
        ),
    ]
