# Generated by Django 6.0.4 on 2026-05-04 18:52

import django.db.models.deletion
import django_enum.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_jobseeker_created_at_jobseeker_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='language')),
                ('proficiency', django_enum.fields.EnumPositiveSmallIntegerField(choices=[(0, 'Basic'), (1, 'Intermediate'), (2, 'Fluent'), (3, 'Native')], default=1)),
                ('jobseeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='accounts.jobseeker', verbose_name='job seeker')),
            ],
            options={
                'verbose_name': 'language',
                'verbose_name_plural': 'languages',
                'db_table': 'languages',
                'ordering': ['name'],
                'constraints': [models.CheckConstraint(condition=models.Q(('proficiency__in', [0, 1, 2, 3])), name='accounts_Language_proficiency_LanguageLevelEnum')],
            },
        ),
    ]
