# Generated by Django 6.0.4 on 2026-05-04 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseeker',
            name='resume_file',
            field=models.FileField(blank=True, default='', upload_to='jobseeker/resumes/', verbose_name='resume file'),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='resume_objective',
            field=models.TextField(blank=True, default='', verbose_name='resume objective'),
        ),
    ]
