# Generated by Django 6.0.4 on 2026-05-05 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_jobseeker_resume_file_jobseeker_resume_objective'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobseeker',
            name='resume_file',
        ),
    ]
