# Generated by Django 6.0.4 on 2026-05-16 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_remove_jobseeker_resume_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseeker',
            name='auto_apply_cover_letter',
            field=models.TextField(blank=True, default='', help_text='Default cover letter used when auto-applying to jobs.', verbose_name='auto apply cover letter'),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='auto_apply_threshold',
            field=models.CharField(default='high', help_text='Minimum suitability level for automatic application: "high" or "medium".', max_length=10, verbose_name='auto apply threshold'),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='is_active_search',
            field=models.BooleanField(default=False, help_text='When enabled, the system automatically finds matching jobs and applies.', verbose_name='active search'),
        ),
    ]
