# Generated by Django 6.0.4 on 2026-05-16 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_jobseeker_auto_apply_cover_letter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseeker',
            name='lang',
            field=models.CharField(choices=[('en', 'English'), ('ru', 'Russian')], default='en', help_text='Preferred language for AI-generated job advice.', max_length=10, verbose_name='language'),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='auto_apply_threshold',
            field=models.CharField(choices=[('high', 'High — only auto-apply for high suitability matches'), ('medium', 'Medium — auto-apply for medium and high suitability matches')], default='high', help_text='Minimum suitability level for automatic application: "high" or "medium".', max_length=10, verbose_name='auto apply threshold'),
        ),
    ]
