POST_VACANCY = 'dashboard/company/post-vacancy.html'
EDIT_VACANCY = 'dashboard/company/edit-vacancy.html'
MANAGE_VACANCIES = 'dashboard/company/manage-vacancies.html'
APPLICANTS_LIST = 'dashboard/company/applicants-list.html'
CANDIDATE_VIEW = 'dashboard/company/candidate-view.html'
