from django.urls import path

from server.apps.dashboard import views

urlpatterns = [
    path('', views.HomePageView.as_view(), name='home'),
    path(
        'jobseeker/saved-jobs/',
        views.SavedJobsView.as_view(),
        name='saved-jobs',
    ),
    path(
        'jobseeker/saved-jobs/<int:pk>',
        views.SavedJobsView.as_view(),
        name='saved-jobs',
    ),
    path(
        'jobseeker/my-applications/',
        views.MyApplicationsView.as_view(),
        name='my-applications',
    ),
    path(
        'jobseeker/my-applications/<int:pk>/',
        views.ApplicationDetailView.as_view(),
        name='application-detail',
    ),
    path(
        'jobseeker/profile/',
        views.CandidateProfileView.as_view(),
        name='candidate-profile',
    ),
    path(
        'jobseeker/profile/edit/',
        views.EditProfileView.as_view(),
        name='edit-profile',
    ),
    path(
        'jobseeker/profile/education/create/',
        views.EducationCreateView.as_view(),
        name='education-create',
    ),
    path(
        'jobseeker/profile/education/<int:pk>/update/',
        views.EducationUpdateView.as_view(),
        name='education-update',
    ),
    path(
        'jobseeker/profile/education/<int:pk>/delete/',
        views.EducationDeleteView.as_view(),
        name='education-delete',
    ),
    path(
        'jobseeker/profile/experience/create/',
        views.ExperienceCreateView.as_view(),
        name='experience-create',
    ),
    path(
        'jobseeker/profile/experience/<int:pk>/update/',
        views.ExperienceUpdateView.as_view(),
        name='experience-update',
    ),
    path(
        'jobseeker/profile/experience/<int:pk>/delete/',
        views.ExperienceDeleteView.as_view(),
        name='experience-delete',
    ),
    path(
        'jobseeker/profile/skills/add/',
        views.SkillAddView.as_view(),
        name='skill-add',
    ),
    path(
        'jobseeker/profile/skills/<int:pk>/remove/',
        views.SkillRemoveView.as_view(),
        name='skill-remove',
    ),
    path(
        'jobseeker/profile/skills/search/',
        views.SkillSearchView.as_view(),
        name='skill-search',
    ),
    path(
        'jobseeker/profile/language/create/',
        views.LanguageCreateView.as_view(),
        name='language-create',
    ),
    path(
        'jobseeker/profile/language/<int:pk>/update/',
        views.LanguageUpdateView.as_view(),
        name='language-update',
    ),
    path(
        'jobseeker/profile/language/<int:pk>/delete/',
        views.LanguageDeleteView.as_view(),
        name='language-delete',
    ),
    path(
        'jobseeker/settings/privacy/',
        views.PrivacySettingsView.as_view(),
        name='settings-privacy',
    ),
    path(
        'jobseeker/settings/password/',
        views.ChangePasswordView.as_view(),
        name='settings-password',
    ),
]
