from django.urls import path

from server.apps.dashboard import views

urlpatterns = [
    path(
        'jobseeker/saved-jobs/',
        views.SavedJobsView.as_view(),
        name='saved-jobs',
    ),
    path(
        'jobseeker/saved-jobs/<int:pk>',
        views.SavedJobsView.as_view(),
        name='saved-jobs',
    ),
    path(
        'jobseeker/my-applications/',
        views.MyApplicationsView.as_view(),
        name='my-applications',
    ),
    path(
        'jobseeker/my-applications/<int:pk>/',
        views.ApplicationDetailView.as_view(),
        name='application-detail',
    ),
    path(
        'jobseeker/profile/',
        views.CandidateProfileView.as_view(),
        name='candidate-profile',
    ),
    path(
        'jobseeker/profile/edit/',
        views.EditProfileView.as_view(),
        name='edit-profile',
    ),
    path(
        'jobseeker/profile/resume/edit/',
        views.ResumeEditView.as_view(),
        name='resume-edit',
    ),
    path(
        'jobseeker/profile/resume/pdf/',
        views.ResumePDFView.as_view(),
        name='resume-pdf',
    ),
    path(
        'jobseeker/profile/education/create/',
        views.EducationCreateView.as_view(),
        name='education-create',
    ),
    path(
        'jobseeker/profile/education/<int:pk>/update/',
        views.EducationUpdateView.as_view(),
        name='education-update',
    ),
    path(
        'jobseeker/profile/education/<int:pk>/delete/',
        views.EducationDeleteView.as_view(),
        name='education-delete',
    ),
    path(
        'jobseeker/profile/experience/create/',
        views.ExperienceCreateView.as_view(),
        name='experience-create',
    ),
    path(
        'jobseeker/profile/experience/<int:pk>/update/',
        views.ExperienceUpdateView.as_view(),
        name='experience-update',
    ),
    path(
        'jobseeker/profile/experience/<int:pk>/delete/',
        views.ExperienceDeleteView.as_view(),
        name='experience-delete',
    ),
    path(
        'jobseeker/profile/skills/add/',
        views.SkillAddView.as_view(),
        name='skill-add',
    ),
    path(
        'jobseeker/profile/skills/<int:pk>/remove/',
        views.SkillRemoveView.as_view(),
        name='skill-remove',
    ),
    path(
        'jobseeker/profile/skills/search/',
        views.SkillSearchView.as_view(),
        name='skill-search',
    ),
    path(
        'jobseeker/profile/language/create/',
        views.LanguageCreateView.as_view(),
        name='language-create',
    ),
    path(
        'jobseeker/profile/language/<int:pk>/update/',
        views.LanguageUpdateView.as_view(),
        name='language-update',
    ),
    path(
        'jobseeker/profile/language/<int:pk>/delete/',
        views.LanguageDeleteView.as_view(),
        name='language-delete',
    ),
    path(
        'jobseeker/settings/privacy/',
        views.PrivacySettingsView.as_view(),
        name='settings-privacy',
    ),
    path(
        'jobseeker/settings/password/',
        views.ChangePasswordView.as_view(),
        name='settings-password',
    ),
    path(
        'company/',
        views.EmployerDashboardView.as_view(),
        name='employer-dashboard',
    ),
    path(
        'company/post-vacancy/',
        views.PostVacancyView.as_view(),
        name='post-vacancy',
    ),
    path(
        'company/vacancies/<int:pk>/edit/',
        views.EditVacancyView.as_view(),
        name='edit-vacancy',
    ),
    path(
        'company/manage-vacancies/',
        views.ManageVacanciesView.as_view(),
        name='manage-vacancies',
    ),
    path(
        'company/vacancies/<int:pk>/toggle/',
        views.ToggleVacancyStatusView.as_view(),
        name='toggle-vacancy',
    ),
    path(
        'company/applicants-list/',
        views.ApplicantsListView.as_view(),
        name='applicants-list',
    ),
    path(
        'company/applications/<int:pk>/status/',
        views.UpdateApplicationStatusView.as_view(),
        name='update-application-status',
    ),
    path(
        'company/applications/<int:pk>/feedback/',
        views.UpdateApplicationFeedbackView.as_view(),
        name='update-application-feedback',
    ),
    path(
        'company/browse-candidates/',
        views.BrowseCandidatesView.as_view(),
        name='browse-candidates',
    ),
    path(
        'company/candidates/<int:pk>/',
        views.CandidateView.as_view(),
        name='candidate-view',
    ),
    path(
        'company/candidates/<int:pk>/resume-pdf/',
        views.CandidateResumePDFView.as_view(),
        name='candidate-resume-pdf',
    ),
]
