# Generated by Django 6.0.4 on 2026-04-29 10:27

import django.db.models.deletion
import django_enum.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_remove_company_accounts_company_size_companysizeenum_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Industries',
                'db_table': 'industries',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, verbose_name='company name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='company email')),
                ('size', django_enum.fields.EnumPositiveSmallIntegerField(choices=[(0, '1-50 employees'), (1, '51-200 employees'), (2, '201-500 employees'), (3, '500+ employees')], default=0)),
                ('website', models.CharField(blank=True, max_length=150)),
                ('recruiter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company', to='accounts.recruiter')),
                ('industry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='companies.industry')),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'db_table': 'companies',
                'constraints': [models.CheckConstraint(condition=models.Q(('size__in', [0, 1, 2, 3])), name='companies_Company_size_CompanySizeEnum')],
            },
        ),
    ]
