# Generated by Django 6.0.4 on 2026-05-03 18:42

import django.db.models.deletion
import django_enum.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='hr_contact_email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='HR contact email'),
        ),
        migrations.AddField(
            model_name='company',
            name='hr_contact_name',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='HR contact name'),
        ),
        migrations.AddField(
            model_name='company',
            name='hr_contact_position',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='HR contact position'),
        ),
        migrations.CreateModel(
            name='StudentProgram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200, verbose_name='program title')),
                ('description', models.TextField(blank=True, default='', verbose_name='description')),
                ('status', django_enum.fields.EnumPositiveSmallIntegerField(choices=[(0, 'Applications Open'), (1, 'Starting Soon'), (2, 'Ongoing'), (3, 'Closed')], default=0)),
                ('url', models.URLField(blank=True, default='', verbose_name='program URL')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_programs', to='company.company')),
            ],
            options={
                'verbose_name': 'Student Program',
                'verbose_name_plural': 'Student Programs',
                'db_table': 'student_programs',
                'ordering': ['-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('status__in', [0, 1, 2, 3])), name='company_StudentProgram_status_ProgramStatusEnum')],
            },
        ),
    ]
