# Generated by Django 6.0.4 on 2026-05-03 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_company_hr_contact_email_company_hr_contact_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='is_verified',
        ),
    ]
