# Generated by Django 6.0.4 on 2026-05-03 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_remove_company_is_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='facebook_url',
        ),
        migrations.RemoveField(
            model_name='company',
            name='instagram_url',
        ),
    ]
