# Generated by Django 6.0.4 on 2026-05-11 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_remove_company_facebook_url_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='benefit',
            options={'ordering': ['name'], 'verbose_name': 'Benefit', 'verbose_name_plural': 'Benefits'},
        ),
        migrations.AlterModelOptions(
            name='industry',
            options={'ordering': ['name'], 'verbose_name': 'Industry', 'verbose_name_plural': 'Industries'},
        ),
    ]
