# Generated by Django 6.0.4 on 2026-05-09 22:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_create_rooms_for_existing_applications'),
        ('jobs', '0006_alter_job_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='jobseeker_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='direct_chat_rooms_as_jobseeker', to=settings.AUTH_USER_MODEL, verbose_name='jobseeker user'),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='recruiter_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='direct_chat_rooms_as_recruiter', to=settings.AUTH_USER_MODEL, verbose_name='recruiter user'),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='application',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_room', to='jobs.jobapplication', verbose_name='application'),
        ),
    ]
