# Generated by Django 6.0.4 on 2026-05-11 13:28

import datetime
import django.db.models.deletion
import django_enum.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0013_remove_jobseeker_resume_file'),
        ('jobs', '0006_alter_job_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('difficulty', django_enum.fields.EnumPositiveSmallIntegerField(choices=[(0, 'Easy'), (1, 'Medium'), (2, 'Hard')], default=0, verbose_name='difficulty')),
                ('questions', models.JSONField(help_text='Structured test questions: [{"question": str, "variants": [str], "correct_index": int}]', verbose_name='questions')),
                ('expires_at', models.DateTimeField(verbose_name='expires at')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_tests', to='jobs.skill', verbose_name='skill')),
            ],
            options={
                'verbose_name': 'skill test',
                'verbose_name_plural': 'skill tests',
                'db_table': 'skill_tests',
            },
        ),
        migrations.CreateModel(
            name='SkillTestAttempt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('answers', models.JSONField(help_text='{"question_index": chosen_variant_index}', verbose_name='answers')),
                ('score', models.PositiveIntegerField(help_text='Percentage score (0-100)', verbose_name='score')),
                ('passed', models.BooleanField(default=False, verbose_name='passed')),
                ('jobseeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_test_attempts', to='accounts.jobseeker', verbose_name='job seeker')),
                ('skill_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='skill_tests.skilltest', verbose_name='skill test')),
            ],
            options={
                'verbose_name': 'skill test attempt',
                'verbose_name_plural': 'skill test attempts',
                'db_table': 'skill_test_attempts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SkillVerification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('difficulty', django_enum.fields.EnumPositiveSmallIntegerField(choices=[(0, 'Easy'), (1, 'Medium'), (2, 'Hard')], default=0, verbose_name='difficulty')),
                ('best_score', models.PositiveIntegerField(help_text='Highest score achieved for this skill', verbose_name='best score')),
                ('verified_at', models.DateTimeField(auto_now=True, verbose_name='verified at')),
                ('jobseeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_verifications', to='accounts.jobseeker', verbose_name='job seeker')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='jobs.skill', verbose_name='skill')),
            ],
            options={
                'verbose_name': 'skill verification',
                'verbose_name_plural': 'skill verifications',
                'db_table': 'skill_verifications',
            },
        ),
        migrations.AddIndex(
            model_name='skilltest',
            index=models.Index(fields=['skill', 'difficulty'], name='skill_tests_skill_i_6d3873_idx'),
        ),
        migrations.AddIndex(
            model_name='skilltest',
            index=models.Index(fields=['expires_at'], name='skill_tests_expires_267035_idx'),
        ),
        migrations.AddConstraint(
            model_name='skilltest',
            constraint=models.UniqueConstraint(condition=models.Q(('expires_at__gt', datetime.datetime(2026, 5, 11, 13, 28, 44, 130439, tzinfo=datetime.timezone.utc))), fields=('skill', 'difficulty'), name='unique_active_skill_test'),
        ),
        migrations.AddConstraint(
            model_name='skilltest',
            constraint=models.CheckConstraint(condition=models.Q(('difficulty__in', [0, 1, 2])), name='skill_tests_SkillTest_difficulty_SkillTestDifficultyEnum'),
        ),
        migrations.AddIndex(
            model_name='skilltestattempt',
            index=models.Index(fields=['jobseeker', 'skill_test'], name='skill_test__jobseek_a66895_idx'),
        ),
        migrations.AddConstraint(
            model_name='skillverification',
            constraint=models.UniqueConstraint(fields=('jobseeker', 'skill'), name='unique_skill_verification_per_jobseeker'),
        ),
        migrations.AddConstraint(
            model_name='skillverification',
            constraint=models.CheckConstraint(condition=models.Q(('difficulty__in', [0, 1, 2])), name='skill_tests_SkillVerification_difficulty_SkillTestDifficultyEnum'),
        ),
    ]
