# Generated by Django 6.0.4 on 2026-05-11 14:15

import django_enum.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_alter_job_description'),
        ('skill_tests', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='skilltest',
            name='unique_active_skill_test',
        ),
        migrations.AddField(
            model_name='skilltest',
            name='error_message',
            field=models.TextField(blank=True, default='', verbose_name='error message'),
        ),
        migrations.AddField(
            model_name='skilltest',
            name='status',
            field=django_enum.fields.EnumPositiveSmallIntegerField(choices=[(0, 'Pending'), (1, 'Ready'), (2, 'Failed')], default=0, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='skilltest',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='expires at'),
        ),
        migrations.AlterField(
            model_name='skilltest',
            name='questions',
            field=models.JSONField(blank=True, help_text='Structured test questions: [{"question": str, "variants": [str], "correct_index": int}]', null=True, verbose_name='questions'),
        ),
        migrations.AddIndex(
            model_name='skilltest',
            index=models.Index(fields=['status'], name='skill_tests_status_8279f4_idx'),
        ),
        migrations.AddConstraint(
            model_name='skilltest',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', [0, 1, 2])), name='skill_tests_SkillTest_status_SkillTestStatusEnum'),
        ),
    ]
