# Generated by Django 6.0.4 on 2026-05-11 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill_tests', '0002_remove_skilltest_unique_active_skill_test_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skilltest',
            name='language',
            field=models.CharField(default='en', help_text='Language code for test questions (e.g. "en", "ru")', max_length=10, verbose_name='language'),
        ),
    ]
