# Generated by Django 6.0.4 on 2026-05-17 20:44

import django.db.models.deletion
import django_enum.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0005_alter_benefit_options_alter_industry_options'),
        ('jobs', '0008_alter_job_id_alter_jobapplication_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_type', django_enum.fields.EnumPositiveSmallIntegerField(choices=[(0, 'praca.by')], default=0)),
                ('external_url', models.URLField(help_text='URL of the company page on the external resource', max_length=500, verbose_name='external url')),
                ('last_synced_at', models.DateTimeField(blank=True, null=True, verbose_name='last synced at')),
                ('sync_status', django_enum.fields.EnumPositiveSmallIntegerField(choices=[(0, 'Never synced'), (1, 'In progress'), (2, 'Completed'), (3, 'Failed')], default=0)),
                ('error_message', models.TextField(blank=True, default='', verbose_name='error message')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_sources', to='company.company', verbose_name='company')),
            ],
            options={
                'verbose_name': 'external source',
                'verbose_name_plural': 'external sources',
                'db_table': 'external_sources',
            },
        ),
        migrations.CreateModel(
            name='ExternalJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_type', django_enum.fields.EnumPositiveSmallIntegerField(choices=[(0, 'praca.by')], default=0)),
                ('external_url', models.URLField(max_length=500, verbose_name='external url')),
                ('external_id', models.CharField(db_index=True, max_length=100, verbose_name='external id')),
                ('raw_data', models.JSONField(blank=True, default=dict, help_text='Raw parsed data from the external source', verbose_name='raw data')),
                ('status', django_enum.fields.EnumPositiveSmallIntegerField(choices=[(0, 'Pending'), (1, 'Synced'), (2, 'Skipped'), (3, 'Failed')], default=0)),
                ('error_message', models.TextField(blank=True, default='', verbose_name='error message')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_jobs', to='company.company', verbose_name='company')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='external_jobs', to='jobs.job', verbose_name='job')),
                ('external_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_jobs', to='job_sync.externalsource', verbose_name='external source')),
            ],
            options={
                'verbose_name': 'external job',
                'verbose_name_plural': 'external jobs',
                'db_table': 'external_jobs',
            },
        ),
        migrations.AddConstraint(
            model_name='externalsource',
            constraint=models.UniqueConstraint(fields=('company', 'source_type'), name='unique_company_source_type'),
        ),
        migrations.AddConstraint(
            model_name='externalsource',
            constraint=models.CheckConstraint(condition=models.Q(('source_type__in', [0])), name='job_sync_ExternalSource_source_type_SourceTypeEnum'),
        ),
        migrations.AddConstraint(
            model_name='externalsource',
            constraint=models.CheckConstraint(condition=models.Q(('sync_status__in', [0, 1, 2, 3])), name='job_sync_ExternalSource_sync_status_SyncStatusEnum'),
        ),
        migrations.AddConstraint(
            model_name='externaljob',
            constraint=models.UniqueConstraint(fields=('external_url',), name='unique_external_job_url'),
        ),
        migrations.AddConstraint(
            model_name='externaljob',
            constraint=models.CheckConstraint(condition=models.Q(('source_type__in', [0])), name='job_sync_ExternalJob_source_type_SourceTypeEnum'),
        ),
        migrations.AddConstraint(
            model_name='externaljob',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', [0, 1, 2, 3])), name='job_sync_ExternalJob_status_ExternalJobStatusEnum'),
        ),
    ]
