# Generated by Django 6.0.4 on 2026-05-17 21:42

import django_enum.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_alter_benefit_options_alter_industry_options'),
        ('job_sync', '0001_initial'),
        ('jobs', '0008_alter_job_id_alter_jobapplication_id_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='externaljob',
            name='job_sync_ExternalJob_source_type_SourceTypeEnum',
        ),
        migrations.RemoveConstraint(
            model_name='externalsource',
            name='job_sync_ExternalSource_source_type_SourceTypeEnum',
        ),
        migrations.AlterField(
            model_name='externaljob',
            name='source_type',
            field=django_enum.fields.EnumPositiveSmallIntegerField(choices=[(0, 'praca.by'), (1, 'career.habr.com')], default=0),
        ),
        migrations.AlterField(
            model_name='externalsource',
            name='source_type',
            field=django_enum.fields.EnumPositiveSmallIntegerField(choices=[(0, 'praca.by'), (1, 'career.habr.com')], default=0),
        ),
        migrations.AddConstraint(
            model_name='externaljob',
            constraint=models.CheckConstraint(condition=models.Q(('source_type__in', [0, 1])), name='job_sync_ExternalJob_source_type_SourceTypeEnum'),
        ),
        migrations.AddConstraint(
            model_name='externalsource',
            constraint=models.CheckConstraint(condition=models.Q(('source_type__in', [0, 1])), name='job_sync_ExternalSource_source_type_SourceTypeEnum'),
        ),
    ]
