# Generated by Django 6.0.4 on 2026-05-03 22:31

import django.db.models.deletion
import django_enum.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_remove_company_accounts_company_size_companysizeenum_and_more'),
        ('company', '0004_remove_company_facebook_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'skill',
                'verbose_name_plural': 'skills',
                'db_table': 'skills',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('description', models.TextField(blank=True, default='', verbose_name='description')),
                ('experience_level', django_enum.fields.EnumPositiveSmallIntegerField(choices=[(0, "Doesn't matter"), (1, 'No experience'), (2, 'From 1 year to 3 years'), (3, 'From 3 to 6 years'), (4, 'More than 6 years')], default=2)),
                ('work_format', django_enum.fields.EnumPositiveSmallIntegerField(choices=[(0, 'Remote'), (1, 'Hybrid'), (2, 'On-site')], default=0)),
                ('schedule', django_enum.fields.EnumPositiveSmallIntegerField(choices=[(0, 'Fixed hours'), (1, 'Flexible hours')], default=1)),
                ('employment_type', django_enum.fields.EnumPositiveSmallIntegerField(choices=[(0, 'Full-time'), (1, 'Part-time'), (2, 'Internship')], default=0)),
                ('salary_min', models.PositiveIntegerField(blank=True, null=True, verbose_name='salary min')),
                ('salary_max', models.PositiveIntegerField(blank=True, null=True, verbose_name='salary max')),
                ('location', models.CharField(blank=True, default='', max_length=150, verbose_name='location')),
                ('is_student_friendly', models.BooleanField(default=False, verbose_name='student friendly')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('posted_at', models.DateTimeField(auto_now_add=True, verbose_name='posted at')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='company.company', verbose_name='company')),
                ('skills', models.ManyToManyField(blank=True, related_name='jobs', to='jobs.skill', verbose_name='skills')),
            ],
            options={
                'verbose_name': 'job',
                'verbose_name_plural': 'jobs',
                'db_table': 'jobs',
                'ordering': ['-posted_at'],
            },
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', django_enum.fields.EnumPositiveSmallIntegerField(choices=[(0, 'Pending'), (1, 'Reviewed'), (2, 'Accepted'), (3, 'Rejected')], default=0)),
                ('applied_at', models.DateTimeField(auto_now_add=True, verbose_name='applied at')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.job', verbose_name='job')),
                ('jobseeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='accounts.jobseeker', verbose_name='job seeker')),
            ],
            options={
                'verbose_name': 'job application',
                'verbose_name_plural': 'job applications',
                'db_table': 'job_applications',
                'ordering': ['-applied_at'],
                'constraints': [models.UniqueConstraint(fields=('job', 'jobseeker'), name='unique_job_application'), models.CheckConstraint(condition=models.Q(('status__in', [0, 1, 2, 3])), name='jobs_JobApplication_status_StatusEnum')],
            },
        ),
        migrations.CreateModel(
            name='SavedJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('saved_at', models.DateTimeField(auto_now_add=True, verbose_name='saved at')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='jobs.job', verbose_name='job')),
                ('jobseeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_jobs', to='accounts.jobseeker', verbose_name='job seeker')),
            ],
            options={
                'verbose_name': 'saved job',
                'verbose_name_plural': 'saved jobs',
                'db_table': 'saved_jobs',
                'ordering': ['-saved_at'],
                'constraints': [models.UniqueConstraint(fields=('job', 'jobseeker'), name='unique_saved_job')],
            },
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['experience_level'], name='jobs_experie_96c339_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['is_active', '-posted_at'], name='jobs_is_acti_e2c030_idx'),
        ),
        migrations.AddConstraint(
            model_name='job',
            constraint=models.CheckConstraint(condition=models.Q(('experience_level__in', [0, 1, 2, 3, 4])), name='jobs_Job_experience_level_ExperienceLevelEnum'),
        ),
        migrations.AddConstraint(
            model_name='job',
            constraint=models.CheckConstraint(condition=models.Q(('work_format__in', [0, 1, 2])), name='jobs_Job_work_format_WorkFormatEnum'),
        ),
        migrations.AddConstraint(
            model_name='job',
            constraint=models.CheckConstraint(condition=models.Q(('schedule__in', [0, 1])), name='jobs_Job_schedule_ScheduleEnum'),
        ),
        migrations.AddConstraint(
            model_name='job',
            constraint=models.CheckConstraint(condition=models.Q(('employment_type__in', [0, 1, 2])), name='jobs_Job_employment_type_EmploymentTypeEnum'),
        ),
    ]
