# Generated by Django 6.0.4 on 2026-05-04 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='cover_letter',
            field=models.TextField(blank=True, default='', verbose_name='cover letter'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='employer_feedback',
            field=models.TextField(blank=True, default='', verbose_name='employer feedback'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='resume',
            field=models.FileField(blank=True, upload_to='applications/resumes/', verbose_name='resume'),
        ),
    ]
