# Generated by Django 6.0.4 on 2026-05-05 15:02

import django_enum.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_jobseeker_resume_file_jobseeker_resume_objective'),
        ('jobs', '0003_remove_jobapplication_jobs_jobapplication_status_statusenum_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='jobapplication',
            name='jobs_JobApplication_status_StatusEnum',
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=django_enum.fields.EnumPositiveSmallIntegerField(choices=[(0, 'Pending'), (1, 'Accepted'), (2, 'Rejected')], default=0),
        ),
        migrations.AddConstraint(
            model_name='jobapplication',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', [0, 1, 2])), name='jobs_JobApplication_status_StatusEnum'),
        ),
    ]
