# Generated by Django 6.0.4 on 2026-05-05 21:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_remove_jobapplication_jobs_jobapplication_status_statusenum_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='views_count',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='views count'),
        ),
        migrations.CreateModel(
            name='JobView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session_key', models.CharField(db_index=True, max_length=40, verbose_name='session key')),
                ('viewed_at', models.DateTimeField(auto_now_add=True, verbose_name='viewed at')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_records', to='jobs.job', verbose_name='job')),
                ('viewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_views', to=settings.AUTH_USER_MODEL, verbose_name='viewer')),
            ],
            options={
                'verbose_name': 'job view',
                'verbose_name_plural': 'job views',
                'db_table': 'job_views',
                'ordering': ['-viewed_at'],
                'indexes': [models.Index(fields=['job', '-viewed_at'], name='job_views_job_id_4ba144_idx')],
                'constraints': [models.UniqueConstraint(fields=('job', 'session_key'), name='unique_job_view_per_session')],
            },
        ),
    ]
