# Generated by Django 6.0.4 on 2026-05-09 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_job_views_count_jobview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.TextField(verbose_name='description'),
        ),
    ]
