# Generated by Django 6.0.4 on 2026-05-16 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_alter_job_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='is_auto_applied',
            field=models.BooleanField(default=False, help_text='Whether this application was created automatically by the active search feature.', verbose_name='auto applied'),
        ),
    ]
